<?xml version="1.0"?>
<package format="3">
  <name>stewart</name>
  <version>0.0.0</version>
  <description>Gazebo Stewart platform model and ROS 2 controller plugin.</description>

  <maintainer email="ingramds@appstate.edu">Daniel Ingram</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>eigen</depend>
  <depend>gazebo_dev</depend>
  <depend>gazebo_ros</depend>
  <depend>geometry_msgs</depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <exec_depend>joy</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
