<?xml version="1.0"?>
<package format="3">
  <name>satellite_tracker</name>
  <version>0.1.0</version>
  <description>Satellite terminal tracking algorithms and ROS 2 adapter node.</description>
  <maintainer email="kerim@example.com">Kerim</maintainer>
  <license>MIT</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>std_msgs</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
