<?xml version="1.0"?>
<package format="3">
  <name>mergen_estimation</name>
  <version>0.1.0</version>
  <description>Mergen IMU kestirim ve filtreleme paketi.</description>
  <maintainer email="unis@example.com">UniS Yazilim Ekibi</maintainer>
  <license>MIT</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <depend>rclcpp</depend>
  <depend>sensor_msgs</depend>
  <depend>mergen_interfaces</depend>
</package>
